ProxyMode=0
Server=zabbix-server
Hostname=proxy-cloud-web-02
DBName=/var/lib/zabbix/db_data/zabbix-proxy.sqlite
StartPollers=5
StartIPMIPollers=0
StartHTTPPollers=3
StartJavaPollers=0
StartVMwareCollectors=0
StartDiscoverers=0
StartPingers=1
Timeout=10
TLSConnect=psk
TLSPSKIdentity=proxy-cloud-web-02
TLSPSKFile=/var/lib/zabbix/enc/proxy-cloud-web-02.psk
