ProxyMode=0
Server=zabbix-server
Hostname=proxy-onprem-snmp-ipmi
DBName=/var/lib/zabbix/db_data/zabbix-proxy.sqlite
StartPollers=5
StartIPMIPollers=3
StartHTTPPollers=0
StartJavaPollers=0
StartVMwareCollectors=0
StartDiscoverers=0
StartPingers=1
Timeout=10
TLSConnect=unencrypted
